name: build

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    # æ¨©é™è¨±å¯
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v2
      # ã„ã¤ã‚‚ã®Build
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: install dependencies
        run: npm ci
      - name: build
        run: npm run build
      # S3ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰
      - name: Deploy to S3
        # S3ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰ç”¨ã®ãƒ¦ãƒ¼ã‚¶ãƒ¼ã‚’ä½œæˆã—ãŸã‚‚ã‚‰ã†ã»ã†ãŒãƒ™ã‚¿ãƒ¼
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run:
          aws s3 sync --delete --region ap-northeast-1 ./dist/ s3://gha-s3-sample/${{ github.sha }}/
      # hashå€¤ã‚’ã‚‚ã¨ã«ã‚³ãƒ¡ãƒ³ãƒˆä½œæˆ
      # ã‚ˆã—ãªã«ã‚³ãƒ¡ãƒ³ãƒˆã®æ›´æ–°ã‚‚ã—ã‚Œãã‚Œã‚‹
      - name: Create comments
        uses: mshick/add-pr-comment@v2
        # URLãŒã»ã¼ç›´æ‰“ã¡ãªã®ã«æ³¨æ„
        with:
          message: |
            æœ€æ–°ã®Deployå…ˆã¯ã“ã¡ã‚‰ï¼ğŸ¦ˆ
            [https://gha-s3-sample.s3.ap-northeast-1.amazonaws.com/${{ github.sha }}/index.html](https://gha-s3-sample.s3.ap-northeast-1.amazonaws.com/${{ github.sha }}/index.html)
            